export const existingUser = {
  name: 'Hakeem',
  onboardingCompleted: true,
  smartAccountAddress: '0x3f2a…9c7e',
  linkedWallet: '0x4D91…7e02',
  policy: {
    status: 'Active',
    goal: 'Grow long-term wealth',
    horizon: '10+ years',
    risk: 'Moderate',
    asset: 'BTC / ETH focused',
    liquidity: '20% (stablecoins)',
    ai: 'Prepare and I approve',
  },
  portfolioValue: '$12,428.52',
  portfolioChange: '+12.4%',
  positions: [
    {
      asset: 'Ethereum',
      ticker: 'ETH',
      share: '50%',
      value: '$6,245.32',
      quantity: '2.48 ETH',
      change: '14.2%',
      symbol: '♦',
    },
    {
      asset: 'Bitcoin',
      ticker: 'BTC',
      share: '25%',
      value: '$3,104.21',
      quantity: '0.034 BTC',
      change: '8.1%',
      symbol: '₿',
    },
    {
      asset: 'USD Coin',
      ticker: 'USDC',
      share: '17%',
      value: '$2,078.99',
      quantity: '2,078.99 USDC',
      change: '0.1%',
      symbol: '$',
    },
    {
      asset: 'Avalanche',
      ticker: 'AVAX',
      share: '8%',
      value: '$1,000.00',
      quantity: '12.34 AVAX',
      change: '6.7%',
      symbol: '▲',
    },
  ],
  activity: [
    { title: 'Supplied 500 USDC to Aave', time: '2 hours ago', value: '+500 USDC' },
    { title: 'Swapped AVAX to ETH', time: '3 days ago', value: '+0.48 ETH' },
    { title: 'Received', time: '5 days ago', value: '+1,000 USDC' },
  ],
} as const;
